Added sp for produced detail 470112
DEFRA/epr-common-data-api pull request #63
Opened 2024-11-07 09:54 UTC by SalmanQayyumEviden

2024-11-07 10:48 UTC, hardikkumar-desai-external requested changes

2024-11-07 11:53 UTC, hardikkumar-desai-external commented on src/EPR.CommonDataService.Data/Scripts/Stored Procedures/get-producer-details-by-organisationid.sql
> +    SELECT
just to clearify in your select statement add as for each column name to match above `organisation_size as ProducerSize` etc

2024-11-28 12:38 UTC, SalmanQayyumEviden commented on src/EPR.CommonDataService.Data/Scripts/Stored Procedures/get-producer-details-by-organisationid.sql
> +    SELECT
done

2024-11-29 14:27 UTC, hardikkumar-desai-external submitted a review, later dismissed

2024-12-02 11:04 UTC, SebastianJLTaylor approved these changes
Only reviewing the SP script:

I can see the duplicates are fixed since the join to the latestfile CTE is now in place.
I can also see the new CTE for latest submission and join to this.
This means the count of subsidiaries doesn't get inflated which is better 
I can also see that the LEFT JOIN to latestSubmission CTE has been changed to an INNER JOIN which i think will also be more efficient.

2024-12-02 11:06 UTC, hardikkumar-desai-external approved these changes

2024-12-02 14:11 UTC, JulianYoungEviden approved these changes
Code looks good...

2024-12-02 14:14 UTC, merged